### PR TITLE
Fix global prefix not working with update marker

### LINKED ISSUE #40: Update Marker functionality not working correctly
When using (real) S3 buckets, the update-marker function doesn't work when using a Prefix (as is recommended for the LightningStream code).

I believe this might be because the Update Marker is checked here:

 https://github.com/PowerDNS/simpleblob/blob/main/backends/s3/s3.go#128

which performs a `Load()` of the markerfile, which starts with prepending the `globalPrefix` here:

https://github.com/PowerDNS/simpleblob/blob/main/backends/s3/s3.go#L204

However, the Marker is stored without the Prefix.

The interesting this is that the fallback mechanism at https://github.com/PowerDNS/simpleblob/blob/main/backends/s3/s3.go#L138 also doesn't work: even after the UpdateMarkerForceListInterval is passed, no `LIST` call is performed. Could this be because the `Load()` function doesn't return an error when it can't find the file? Or that that error isn't properly handled?

### PR DESCRIPTION
**Pull request by ahouene**
When using both the update marker and the global prefix options, the marker would be _written without_ the global prefix, and we'd try to _read_ it _with_ the global prefix.

This PR makes sure the global prefix is always used with the update marker.

Closes #40

### CODE REVIEW

**Comment by franklouwers** [comment]
I've been LS running with this patch since Thursday. The good news: it works. The better news: it reduces cost dramatically, so it works.
CleanShot 2023-06-25 at 10 16 41@2x

**Now to the bad news:**

there's a memory (and maybe CPU as well) issue.

I have a simple 2 node test setup, with 3 zones with very few updates, so just to test stability.

Tje setup had been running fairly stable for about 10 days without the marker functionality. I then built a custom LS with this patched-simpleblob included, and enabled the marker feature on June 21st. As you can see from the graph below, a pattern started emerging at that time: there's a mem leak which starts to happen at that same time, leaking to very frequent OOMs.

CleanShot 2023-06-25 at 10 18 33

Unfortunately I only have memory graphs from one of the nodes (it's a test setup), but do see the OOMs on the second node as well. The second node also exhibits increased CPU load. 

As you can see on the graphs, this behaviour only started when I enabled the marker-functionality, with this patch and it didn't happen before.

CleanShot 2023-06-25 at 10 22 27

The 2 test servers are running:

- Ubuntu 22.04 LTS
- dnsdist latest stable release
- pdns auth latest stable release (with only lmdb backend enabled)
- Lightningstream master with this patched simpleblob in

**Comment by ahouene** [comment]
Thank you for the detailed report!

I created #44 to track this memory issue. I think I have found a culprit, that is related to GetObject operations, which matches the metrics you provided.

**Comment by franklouwers** [comment]
@ahouene Seems to work:
CleanShot 2023-06-28 at 14 24 53@2x

File: backends/s3/s3.go [hunk 1]
```diff
@@ -117,9 +117,18 @@ type Backend struct {
...
 	prefix = b.prependGlobalPrefix(prefix)
+	defer func() {
+		if !b.hasGlobalPrefix() {
+			return
+		}
+		for i, blob := range blobList {
+			s, _ := b.cutGlobalPrefix(blob.Name)
+			blobList[i].Name = s
+		}
+	}()
```
Comment (wojas) [inline backends/s3/s3.go:131]: If I read this correctly, by putting all of this in a defer, you are changing the cached values and calling it over and over on existing cached values.

Don't do magic in `defer`, it will bite you.

**Review by wojas — CHANGES_REQUESTED** [review]

**Review by wojas — APPROVED** [review]
Great, a lot clearer now!
